.travis.yml

The latest needs to `run` the script

change:travis.yml

---

README.md
src/client.ts
src/deferred.ts
test.ts

Hi!
At first, I really thank you for making this project and I learned much from this code.
I am watching your code and comparing with node.js mysql lib.
During analyzing your code, I confused a some naming. This is pool in clientconfig object.
I suggest that change the property name as poolSize. I think It's more clear and helpful to other people. :)

clientConfig's pool property naming is vague.

---

README.md

When people would copy paste this they'd fall victim to a vulnerability

remove example with sql-injection

---

deps.ts
src/auth/mysql_native_password.ts

depends on #32
I fix failed fetch error.
Uncaught Error: Import 'https://deno.land/std/strings/mod.ts' failed: 404 Not Found

fix failed fetch std/strings

---

.github/workflows/ci.yml
.github/workflows/wait-for-mysql.sh

depends on #34 
I tried to execute tests were success.
https://github.com/t-yng/deno_mysql/actions/runs/72778009

Fix failed ci unit test with database connection.

---

src/packets/parsers/handshake.ts

MySQL Protocol::Handshake packet:
https://dev.mysql.com/doc/internals/en/connection-phase-packets.html

fix the error of the length of the seed

---

src/packets/parsers/result.ts
test.ts

- This PR tries to resolve #39.
- I don't have any idea about how to test `MYSQL_TYPE_TIME2` value, so any help/suggestion is appreciated!

MySQL's TIME value should be mapped to String instead of Date

---

src/packets/parsers/result.ts
test.ts

This PR tries to resolve #42.
- Fixed to convert MySQL's decimal type to `String`.
- Fixed to convert MySQL's bigint type to `BigInt`.
@manyuanrong @magichim Please review🙏

Fix to convert decimal to String and bigint to BigInt

---

src/packets/parsers/result.ts

Fix bug about treating the decimal and bigint type introduced by #46

---

deps.ts
test.ts

This PR also fixes #62 and adds a test that verifies the issue has been fixed.

Update sql_builder to v1.6.0

---

src/client.ts
src/connection.ts
src/constant/errors.ts
src/deferred.ts
src/pool.ts
test.ts
test.util.ts

Add idle timeout, fix read timeout, and improve error handling

---

deps.ts
mod.ts
src/connection.ts
src/packets/builders/auth.ts
src/packets/parsers/err.ts
src/packets/parsers/result.ts

Add Deno 1.4 support (see #72)

Add import type for imports not used as a value

---

.github/workflows/ci.yml
src/client.ts
src/connection.ts
src/packets/packet.ts
test.deps.ts
test.ts
test.util.ts

Add UNIX Domain Socket support and fix packet writing

---

src/packets/packet.ts

Fix packet header reading

---

.github/workflows/ci.yml
deps.ts
src/buffer.ts
src/packets/parsers/result.ts
test.deps.ts

Update std to 0.74.0 and run test with latest Deno

---

README.md

Fix typo when browsing around.

FIx Typo in the Readme

---

.github/workflows/ci.yml
README.md
src/connection.ts

I just noticed that MariaDB version 10.0 behaves like 10.1.

Add MariaDB 10.0 support

---

src/packets/parsers/result.ts
test.ts

Return TINYINT column values as is

---

README.md
mod.ts
src/logger.ts
test.ts

Add configLogger()

---

deps.ts

This should solve https://github.com/denodrivers/mysql/issues/115

Bumped SQL-builder to v1.9.0

---

.github/workflows/ci.yml
src/auth_plugin/caching_sha2_password.ts
src/auth_plugin/crypt.ts
src/connection.ts

This PR re-implements RSA encryption using the built-in Deno SubtleCrypto API, thus removing the deprecated god_crypto dependency that prevents installation. The installation issue this PR fixes is described in #131.

Migrate RSA to SubtleCrypto

---

.github/workflows/ci.yml
src/connection.ts

Handle EOF_Packet and CLIENT_DEPRECATE_EOF correctly

---

test.ts

Add test for Authentication Method Mismatch

---

src/pool.ts

Don't block the event loop from finishing

---

.github/workflows/ci.yml
src/connection.ts
test.ts

Fix querying empty string
